#!/bin/bash -ex

# check-dependencies
#
# Checks that the dependencies in this project are all in use.

# This actually requires nightly, unavoidably:
#   <https://github.com/est31/cargo-udeps#usage>
cargo +nightly udeps --locked --all-targets
