name: Tests

on:
    push:
        branches:
            - main
    pull_request:

env:
    CARGO_TERM_COLOR: always

jobs:
    test:
        name: Tests
        runs-on: ubuntu-latest

        steps:
            -   name: Check out source tree
                uses: actions/checkout@v2
            -   name: Save & Restore Cache
                uses: actions/cache@v2
                with:
                    path: |
                        ~/.cargo
                        ~/.rustup
                        target
                    key: build-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
            -   name: Run tests
                run: tools/check-tests

    lint:
        name: Lint & style check
        runs-on: ubuntu-latest
        needs: test

        steps:
            -   name: Check out source tree
                uses: actions/checkout@v2
            -   name: Save & Restore Cache
                uses: actions/cache@v2
                with:
                    path: |
                        ~/.cargo
                        ~/.rustup
                        target
                    key: lint-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
            -   name: Install rustup components
                run: rustup component add rustfmt clippy
            -   name: Check lints
                run: tools/check-lints

    dependencies:
        name: Abandoned dependencies check
        runs-on: ubuntu-latest
        needs: test

        steps:
            -   name: Check out source tree
                uses: actions/checkout@v2
            -   name: Save & Restore Cache
                uses: actions/cache@v2
                with:
                    path: |
                        ~/.cargo
                        ~/.rustup
                        target
                    key: dependencies-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
            -   name: Install cargo-udeps
                run: cargo install cargo-udeps
            -   name: Check dependencies
                run: tools/check-dependencies
